name: Deploy to Home Server

on:
  workflow_dispatch:
    inputs:
      github_token:
        description: 'GitHub Token'
        required: true
        type: string
      github_organization:
        description: 'GitHub Organization'
        required: true
        type: string

jobs:
  fetch_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch and update README
        env:
          GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
          GITHUB_ORGANIZATION: ${{ github.event.inputs.github_organization }}
        run: |
          python generate_readme.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
        run: |
          git config --global user.name "IdrisFallout"
          git config --global user.email "waithakasam2017@gmail.com"
          git add README.md
          git commit -m "Update README with organization repository list"

          # Push changes using GitHub API
          curl -X PUT \
            -H "Authorization: token ${PAT}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/IdrisFallout-Selfhosted/.github/contents/profile/README.md \
            -d '{"message": "Update README with organization repository list", "content": "'$(base64 README.md)'" }'

