name: Deploy to Home Server

on:
  workflow_dispatch:
    inputs:
      github_token:
        description: 'GitHub Token'
        required: true
        type: string
      github_organization:
        description: 'GitHub Organization'
        required: true
        type: string
      committer_name:
        description: 'Committer Name'
        required: true
        type: string
      committer_email:
        description: 'Committer Email'
        required: true
        type: string

jobs:
  fetch_repos:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch and update README
        env:
          GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
          GITHUB_ORGANIZATION: ${{ github.event.inputs.github_organization }}
          COMMITTER_NAME: ${{ github.event.inputs.committer_name }}
          COMMITTER_EMAIL: ${{ github.event.inputs.committer_email }}
        run: |
          python generate_readme.py
