name: Deploy to Home Server

on:
  workflow_dispatch:
    inputs:
      github_token:
        description: 'GitHub Token'
        required: true
        type: string
      github_organization:
        description: 'GitHub Organization'
        required: true
        type: string

jobs:
  fetch_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch and print repositories
        env:
          GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
          GITHUB_ORGANIZATION: ${{ github.event.inputs.github_organization }}
        run: python generate_readme.py

      - name: Commit README
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with organization repository list"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
